### ISSUE TITLE
Shippable dictionaries

### ISSUE THREAD

**Issue by sidnarayanan** [sidnarayanan/RedPanda#2]
Dictionaries generated with rootcling have some absolute paths hardcoded in. These can't be shipped to non-T3 worker nodes. In particular, `TSystem::Load` throws:
```
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for /home/snarayan/cms/cmssw/analysis/003/CMSSW_8_0_26_patch1/src/PandaCore/Tools/LinkDef.h
   requested to autoload type EventObj
```
Ask @yiiyama how he made the paths relative for Bambu. I glanced at `genDict.sh`, but I'm not sure I get what specifically made it work.

**Comment by sidnarayanan** [comment]
Actually this seems to have fixed it:

https://github.com/sidnarayanan/RedPanda/blob/cef087bc2e305787ac928557862c404a069e6397/Makefile#L15

I just rely on `ROOT_INCLUDE_PATH` for everything. I can see now why a bash script is preferable to makefile gymnastics. Still need to test the full chain, but it's 3 am.

**Comment by yiiyama** [comment]
`genDict.sh` did the exact same thing.
This is the commit where library include paths were made relative:

https://github.com/cpausmit/MitCommon/commit/8028a63d2a1dffa16eaac03e039c7b5c23ab5160#diff-14ea8c30a07ba365a8f40c9660cd15bb

(The commit is addressing two problems at the same time and it's hard to disentangle)

Since we had `-I$CMSSW_BASE/src` already given to rootcling (looking at your Makefile, though, I guess that was unnecessary), we could be passing the header paths relative to `$CMSSW_BASE/src` as `$HEADERS` (was passing the full paths before), and that made the resulting dictionary portable as long as the user environment has `$CMSSW_BASE/src` in `ROOT_INCLUDE_PATH` (i.e. has `cmsenv` called).

**Comment by sidnarayanan** [comment]
Thanks for the explanation! Yeah, `$CMSSW_BASE/src` is part of `$ROOT_INCLUDE_PATH`.

Actually, I just ended up copying most of `genDict.sh` since it was easier than having multiple makefiles for each package, plus it adds additional include paths based on BuildFiles. The only things I changed were to look explicitly for `LinkDef.h` and adding a `-j NCORES` flag to mimic `make`:

https://github.com/sidnarayanan/PandaCore/blob/dev-submission/bin/genDict
